# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 6) do

  create_table "answer_sheets", :force => true do |t|
    t.column "questionnaire_id", :integer
    t.column "identifier",       :string,  :limit => 100
    t.column "remote_ip",        :string,  :limit => 50
  end

  add_index "answer_sheets", ["questionnaire_id"], :name => "questionnaire_id"

  create_table "answers", :force => true do |t|
    t.column "question_id",      :integer
    t.column "answer_sheet_id",  :integer
    t.column "selected_options", :string,  :limit => 100
    t.column "content",          :text
  end

  add_index "answers", ["question_id"], :name => "question_id"
  add_index "answers", ["answer_sheet_id"], :name => "answer_sheet_id"

  create_table "options", :force => true do |t|
    t.column "question_id", :integer
    t.column "content",     :text
    t.column "order",       :integer
  end

  add_index "options", ["question_id"], :name => "question_id"

  create_table "questionnaires", :force => true do |t|
    t.column "title",       :string
    t.column "description", :text
    t.column "status",      :string, :limit => 20
  end

  create_table "questions", :force => true do |t|
    t.column "questionnaire_id", :integer
    t.column "option_type",      :string,  :limit => 5
    t.column "answer_size",      :string,  :limit => 1
    t.column "show_as_stat",     :boolean,              :default => true
    t.column "content",          :text
    t.column "order",            :integer
  end

  add_index "questions", ["questionnaire_id"], :name => "questionnaire_id"

  add_foreign_key "answer_sheets", ["questionnaire_id"], "questionnaires", ["id"], :on_delete => :cascade, :name => "answer_sheets_ibfk_1"

  add_foreign_key "answers", ["question_id"], "questions", ["id"], :on_delete => :cascade, :name => "answers_ibfk_1"
  add_foreign_key "answers", ["answer_sheet_id"], "answer_sheets", ["id"], :on_delete => :cascade, :name => "answers_ibfk_2"

  add_foreign_key "options", ["question_id"], "questions", ["id"], :on_delete => :cascade, :name => "options_ibfk_1"

  add_foreign_key "questions", ["questionnaire_id"], "questionnaires", ["id"], :on_delete => :cascade, :name => "questions_ibfk_1"

end
